"""add column created_at in UserData

Revision ID: 88a53a5f50d2
Revises: c647eb2f0900
Create Date: 2026-04-01 15:18:19.287209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a53a5f50d2'
down_revision: Union[str, Sequence[str], None] = 'c647eb2f0900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'created_at')
    # ### end Alembic commands ###
