services:
  accounts_service:
    extends:
      file: base.yaml
      service: accounts_service
    command: sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0 --port 8081"

  accounts_db:
    extends:
      file: base.yaml
      service: accounts_db

volumes:
  accounts_db_data:

networks:
  app_network:
    driver: bridge
