server {
    listen 80;

    location /accounts/ {
        proxy_pass http://accounts_service:8081/; 
        proxy_set_header Host $host;
    }

    location /resource/ {
        proxy_pass http://resource_service:8082/;
        proxy_set_header Host $host;
    }
}
