apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Имя сервиса Prometheus в docker-compose
    isDefault: true
    editable: false             # Запретить менять настройки через интерфейс
