services:

  resource_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: resource_db
    volumes:
      - resource_db_data:/var/lib/postgresql/data
    networks:
      - app_network


  resource_redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network


  resource_service:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      IS_TEST_DB: ${IS_TEST_DB:-False}
      PUBLIC_KEY_HEX: ${PUBLIC_KEY_HEX}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    build:
      context: .
      target: ${BUILD_TARGET}
    container_name: resource_service
    depends_on:
      resource_redis:
        condition: service_healthy 
      resource_db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0 --port 8082"
    volumes:
      - .:/project
    ports:
      - "8082:8082"
    networks:
      - app_network

volumes:
  resource_db_data:

networks:
  app_network:
    driver: bridge


# Для CI "command" переопределяется в /accounts/compose.test.yaml
# указанные ниже команды для удобства локальной разработки и тестировани.(copy-past)

# запуск сервера: 
# - command: sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0 --port 8000"

# запуск теста:
# command: sh -c "alembic upgrade head && python -m pytest -s -v"

# проверка покрытия тестов:
# command: sh -c "alembic upgrade head && python -m pytest --cov=app --cov-report=term-missing"
